### ISSUE TITLE
Make compatible with latest PyTorch

### ISSUE THREAD

**Issue by Xieyyyy** [mmuckley/torchkbnufft#71]
Hi,
When I try to import the lib, there raises an error: AttributeError: module 'torch' has no attribute 'complex32'. How can I solve the issue?
Thanks!

**Comment by mmuckley** [comment]
Hello @Xieyyyy, did you install ignoring dependencies? I saw this issue with PyTorch 1.11.

https://github.com/mmuckley/torchkbnufft/blob/4e5acbf3d946d21a60a8c516f123762cf7a625c0/setup.py#L22

**Comment by fschiffers** [comment]
Hi Matthew,

I have the same issue with PyTOrch 1.11.

I just removed the line in utils.py, and my code seemed to run fine. But I'm not sure if changing this has any further implications. 

![image](https://user-images.githubusercontent.com/13521689/183113802-d7d3a4fc-9467-4ef9-acfd-e6bf98f2bd28.png)

**Comment by mmuckley** [comment]
Hello @fschiffers, that code is necessary for proper casting when using the `.to()` function of a module. Otherwise it may convert some tensors to real when they should remain complex.

**Comment by Xieyyyy** [comment]
Thank you for your reply. @mmuckley 
How can I specify the ignoring dependencies? When installing or importing?
Sorry for I am a rookie :)

**Comment by Xieyyyy** [comment]
I have just re-install the lib with the command "pip install torchkbnufft --no-dependencies", but the same issue has raised.

**Comment by mmuckley** [comment]
@Xieyyyy in this case we need to enforce dependencies - the package doesn't work on PyTorch 1.11.

**Comment by mmuckley** [comment]
Solved by PR #77.
